package com.javaprophet.jasm.constant;

public enum CType {
	CLASS, DOUBLE, FIELDREF, FLOAT, INTEGER, INTERFACEMETHODREF, INVOKEDYNAMIC, LONG, METHODHANDLE, METHODREF, METHODTYPE, NAMEANDTYPE, STRING, UTF8;
	
}
